#version: '3.8'

services:
  app:
    image: node:14
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    command: node app.js
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
